// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYXGJUGiRisyMcO4O2apoXtb3ESfquvaI',
    appId: '1:1057888993825:web:11c053b1911f0f61861960',
    messagingSenderId: '1057888993825',
    projectId: 'sistem-proyect-44d70',
    authDomain: 'sistem-proyect-44d70.firebaseapp.com',
    storageBucket: 'sistem-proyect-44d70.firebasestorage.app',
    measurementId: 'G-HBNC0F4PGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1RCPmX3zdQvXlfzca6WE4vIGj8Q5mFlM',
    appId: '1:1057888993825:android:90dc23aa3b5800f9861960',
    messagingSenderId: '1057888993825',
    projectId: 'sistem-proyect-44d70',
    storageBucket: 'sistem-proyect-44d70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvPrQXFsyKT_9U7pppWmIg_jeJolMlB9s',
    appId: '1:1057888993825:ios:13afe28fc0a5e5d6861960',
    messagingSenderId: '1057888993825',
    projectId: 'sistem-proyect-44d70',
    storageBucket: 'sistem-proyect-44d70.firebasestorage.app',
    iosBundleId: 'com.example.sistemProyect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvPrQXFsyKT_9U7pppWmIg_jeJolMlB9s',
    appId: '1:1057888993825:ios:13afe28fc0a5e5d6861960',
    messagingSenderId: '1057888993825',
    projectId: 'sistem-proyect-44d70',
    storageBucket: 'sistem-proyect-44d70.firebasestorage.app',
    iosBundleId: 'com.example.sistemProyect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYXGJUGiRisyMcO4O2apoXtb3ESfquvaI',
    appId: '1:1057888993825:web:e0c708066be35ade861960',
    messagingSenderId: '1057888993825',
    projectId: 'sistem-proyect-44d70',
    authDomain: 'sistem-proyect-44d70.firebaseapp.com',
    storageBucket: 'sistem-proyect-44d70.firebasestorage.app',
    measurementId: 'G-627MM1B4XC',
  );
}
